[theme]
primaryColor = "#764ba2"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
